@echo off
echo Starting ComfyUI server...
start /B python main.py
echo Waiting for server to start...
timeout /t 10 /nobreak
echo Running sprite optimization...
python optimize_sprite_workflow.py
pause