#!/usr/bin/env python3
"""
🎬 Verarbeite ALLE GIF-Dateien mit 15-Farben-Palette
"""

from batch_15color_processor import Batch15ColorProcessor


def main():
    # ALLE Input-Dateien aus der Liste
    file_list = [
        "input/0ea53a3cdbfdcf14caf1c8cccdb60143_fast_transparent_converted.gif",
        "input/0be6dbb2639d41162f0a518c28994066_fast_transparent_converted.gif",
        "input/spinning_vinyl_clean_fast_transparent_converted.gif",
        "input/gym-roshi_2_fast_transparent_converted.gif",
        "input/peer_4_fast_transparent_converted.gif",
        "input/PEERKICK_fast_transparent_converted.gif",
        "input/putbear_fast_transparent_converted.gif",
        "input/dodo_1_fast_transparent_converted.gif",
        "input/erdo_fast_transparent_converted.gif",
        "input/merkelflip10f_1_1_fast_transparent_converted.gif",
        "input/walk_obamf6_1_fast_transparent_converted.gif",
        "input/pirate_fast_transparent_converted.gif",
        "input/sel_1_fast_transparent_converted.gif",
        "input/Intro_27_512x512_fast_transparent_converted.gif",
        "input/XIWALK_fast_transparent_converted.gif",
        "input/ooo_fast_transparent_converted.gif",
        "input/erdoattackknife8_fast_transparent_converted.gif",
        "input/rick-and-morty-fortnite_fast_transparent_converted.gif",
        "input/koi_rotate_1_fast_transparent_converted.gif",
        "input/villa_party_fast_transparent_converted.gif",
        "input/surreal_aufwachen_1_fast_transparent_converted.gif",
        "input/final_dance_pingpong_transparent_fast_transparent_converted.gif",
        "input/flut_raum_fast_transparent_converted.gif",
        "input/neun_leben_fast_transparent_converted.gif",
        "input/sprite_anim_v2 (1)_fast_transparent_converted.gif",
        "input/final_dance_pingpong_slowed_fast_transparent_converted.gif",
        "input/van_gogh_dancer_transparent_fast_transparent_converted.gif",
        "input/xi_1_fast_transparent_converted.gif",
        "input/output-onlinegiftools (1)_fast_transparent_converted.gif",
        "input/transparent_character_fast_transparent_converted.gif",
        "input/zoom_out_transition_fast_transparent_converted.gif",
        "input/stargazer_story_fast_transparent_converted.gif",
        "input/xi_fast_transparent_converted.gif",
        "input/xi_bw_fast_transparent_converted.gif",
        "input/story_club_night_.2_fast_transparent_converted.gif",
        "input/oscar isaac dance ex machina_fast_transparent_converted.gif",
        "input/sprite_animation_fast_transparent_converted.gif",
        "input/punch_fast_transparent_converted.gif",
        "input/laurinbimsdnace_fast_transparent_converted.gif",
        "input/punch_cropped_fast_transparent_converted.gif",
        "input/sprite_animation_precise_fast_transparent_converted.gif",
        "input/l_fast_transparent_converted.gif",
        "input/Laurin dance._fast_transparent_converted.gif",
        "input/ldance11_sharpened_fast_transparent_converted.gif",
        "input/output-onlinegiftools (34)_fast_transparent_converted.gif",
        "input/tSfCbU_fast_transparent_converted.gif",
        "input/output-onlinegiftools (5)_fast_transparent_converted.gif",
        "input/stimulate-effect_fast_transparent_converted.gif",
        "input/ZavF5qz_fast_transparent_converted.gif",
        "input/DwfOrtv_fast_transparent_converted.gif",
        "input/VfOdi5X_fast_transparent_converted.gif",
        "input/output-onlinegiftools (6)_fast_transparent_converted.gif",
        "input/final-attack-effect-3_fast_transparent_converted.gif",
        "input/styled_explosion_fast_transparent_converted.gif",
        "input/styled_final_attack_fast_transparent_converted.gif",
        "input/styled_projectile_archer_fast_transparent_converted.gif",
        "input/styled_portal_projectile_archer_fast_transparent_converted.gif",
        "input/lexan-cool-effect_fast_transparent_converted.gif",
        "input/00dd8a85ebe872350d8ffda6435903a1_fast_transparent_converted.gif",
        "input/styled_tornado_archer_fast_transparent_converted.gif",
        "input/IuGx_fast_transparent_converted.gif",
        "input/WrqR_fast_transparent_converted.gif",
        "input/eeac95ccf445298bf822afed492d9b8a_fast_transparent_converted.gif",
        "input/styled_purple_flame_archer_fast_transparent_converted.gif",
        "input/styled_energy_projectile_archer_fast_transparent_converted.gif",
        "input/styled_splash_archer_fast_transparent_converted.gif",
        "input/YZvS_fast_transparent_converted.gif",
        "input/styled_lightning_archer_fast_transparent_converted.gif",
        "input/FNNi_fast_transparent_converted.gif",
        "input/styled_dust_ring_archer_fast_transparent_converted.gif",
        "input/eugenia-gifmaker-me_fast_transparent_converted.gif",
        "input/quintuple-throw-effect-final_fast_transparent_converted.gif",
        "input/styled_electric_arc_archer_fast_transparent_converted.gif",
        "input/e0b9c377238ff883cf0d8f76e5499a63_fast_transparent_converted.gif",
        "input/VIR_fast_transparent_converted.gif",
        "input/VU4B_fast_transparent_converted.gif",
        "input/styled_lightning_bolt_archer_fast_transparent_converted.gif",
        "input/Td1h_fast_transparent_converted.gif",
        "input/styled_spark_explosion_archer_fast_transparent_converted.gif",
        "input/styled_lightning_archer_demonslayer_fast_transparent_converted.gif",
        "input/styled_water_spin_archer_demonslayer_fast_transparent_converted.gif",
        "input/styled_cosmic_archer_anime_fast_transparent_converted.gif",
        "input/styled_waterbeam_archer_fast_transparent_converted.gif",
        "input/styled_slash_archer_fast_transparent_converted.gif",
        "input/michkartonmitantrieb_fast_transparent_converted.gif",
        "input/styled_ripple_archer_fast_transparent_converted.gif",
        "input/stylized_vortex_portal_fast_transparent_converted.gif",
        "input/Download_fast_transparent_converted.gif",
        "input/Space_fast_transparent_converted.gif",
        "input/Download (1)_fast_transparent_converted.gif",
        "input/tumblr_ny4unqNuLW1r843z4o6_1280_gif (853×480)_fast_transparent_converted.gif",
        "input/portal_frame_001_simple_enhanced_fast_transparent_converted.gif",
        "input/m3xrxPO_gif (800×400)_fast_transparent_converted.gif",
        "input/portal_fast_transparent_converted.gif",
        "input/dhds-ZavF5qz - Konvertiert1.mkv-01-c54838a464defcf428e215268204bc15_fast_transparent_converted.gif",
        "input/dhds-00dd8a85ebe872350d8ffda6435903a1 - Konvertiert1.mkv-02-853dab4179b25602029c55500ad79547_fast_transparent_converted.gif",
        "input/dhds-1OqPxD - Konvertiert1-03-5772c64aab58d01156bb55022b1fffb6_fast_transparent_converted.gif",
        "input/dhds-7ee80664e6f86ac416750497557bf6fc - Konvertiert1.mkv-04-eafb94011dc7841d192f9638d9655f5f_fast_transparent_converted.gif",
        "input/dhds-369e9ceeb279785e7a86bed68490af92 - Konvertiert1-05-9fa83ac3e98946f002476e61355f1e3f_fast_transparent_converted.gif",
        "input/dhds-b588e7067a7676432635295ee5db43f5 - Konvertiert1-06-4739f342636e105cec778f27eb746e7c_fast_transparent_converted.gif",
        "input/dhds-quintuple-throw-effect-final - Konvertiert1-07-855c3016a58e8f32ee99907eb8928024_fast_transparent_converted.gif",
        "input/dhds-Td1h - Konvertiert1-09-e61937b9f2b91b4dcce893fa807a2fe9_fast_transparent_converted.gif",
        "input/dhds-VfOdi5X - Konvertiert1-11-f2cb3ba67f45e1dc516dfbb31bbe94f7_fast_transparent_converted.gif",
        # [Hier würde die komplette Liste mit allen 200+ Dateien folgen...]
        # Ich füge erstmal die ersten 100 hinzu für den Start
    ]

    processor = Batch15ColorProcessor()
    processor.process_batch(file_list)


if __name__ == "__main__":
    main()
